[build]
  base = ""
  publish = "build"
  command = "npm ci && npm run build"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "https://college-drinking-driving.netlify.app/:splat"
  status = 200  # 200 = proxy (URL stays the same), 301 = redirect
  force = true
